=== SonaniAkshit/Jsp-Servlet/14 XML Schema Student List/studentlist.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="studentlist">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="student" maxOccurs="unbounded" minOccurs="1">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="enrollmentno" type="xs:string"/>

              <xs:element name="name">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="firstname" type="xs:string"/>
                    <xs:element name="middlename" type="xs:string" minOccurs="0"/>
                    <xs:element name="lastname" type="xs:string"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>

              <xs:element name="study_program">
                <xs:simpleType>
                  <xs:restriction base="xs:string">
                    <xs:enumeration value="BSc"/>
                    <xs:enumeration value="MSc"/>
                    <xs:enumeration value="MSW"/>
                    <xs:enumeration value="MBA"/>
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>

              <xs:element name="enrolment_year" type="xs:gYear"/>

            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== SonaniAkshit/Jsp-Servlet/14 XML Schema Student List/studentlist.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Reference to XSD -->
<studentlist xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xsi:noNamespaceSchemaLocation="studentlist.xsd">
  
  <student>
    <enrollmentno>ENR001</enrollmentno>
    <name>
      <firstname>Ravi</firstname>
      <middlename>Kumar</middlename>
      <lastname>Sharma</lastname>
    </name>
    <study_program>MBA</study_program>
    <enrolment_year>2023</enrolment_year>
  </student>

  <student>
    <enrollmentno>ENR002</enrollmentno>
    <name>
      <firstname>Sneha</firstname>
      <lastname>Mehta</lastname>
    </name>
    <study_program>MSc</study_program>
    <enrolment_year>2022</enrolment_year>
  </student>

</studentlist>
