=== SonaniAkshit/Jsp-Servlet/15 XML Schema for phonebook/phonebook.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <!-- Root element -->
  <xs:element name="phonebook">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="department" maxOccurs="unbounded" minOccurs="1">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="deptname" type="xs:string"/>
              <xs:element name="deptphone" type="xs:string"/>
              <xs:element name="deptemail" type="xs:string"/>
              <xs:element name="employee" maxOccurs="unbounded" minOccurs="1">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="empid" type="xs:string"/>
                    <xs:element name="empname" type="xs:string"/>
                    <xs:element name="empphone" type="xs:string"/>
                    <xs:element name="empemail" type="xs:string"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== SonaniAkshit/Jsp-Servlet/15 XML Schema for phonebook/phonebook.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Link the XML file with the Schema -->
<phonebook xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:noNamespaceSchemaLocation="phonebook.xsd">

  <department>
    <deptname>Computer Science</deptname>
    <deptphone>079 40016331/326</deptphone>
    <deptemail>cs@gujaratvidyapith.org</deptemail>
    
    <employee>
      <empid>EMP001</empid>
      <empphone>9876543210</empphone>
      <empname>Ravi Sharma</empname>
      <empemail>ravi@gujaratvidyapith.edu</empemail>
    </employee>
    
    <employee>
      <empid>EMP002</empid>
      <empname>Sneha Mehta</empname>
      <empphone>9876543222</empphone>
      <empemail>sneha@gujaratvidyapith.edu</empemail>
    </employee>
  </department>

  <department>
    <deptname>Mathematics</deptname>
    <deptphone>0456-789123</deptphone>
    <deptemail>maths@gujaratvidyapith.edu</deptemail>
    
    <employee>
      <empid>EMP003</empid>
      <empname>Rahul Verma</empname>
      <empphone>9876543233</empphone>
      <empemail>rahul@gujaratvidyapith.edu</empemail>
    </employee>
  </department>

</phonebook>
